customauth/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import logout

from rest_framework.routers import DefaultRouter

from .views import RegisterView, LoginView, APILoginView


app_name = 'customauth'

router = DefaultRouter(trailing_slash=True)
# router.register('login', APILoginView.as_view(), base_name='login')

urlpatterns = [
   url(r'^login/$', LoginView.as_view(), name='login'),
   url(r'^register/$', RegisterView.as_view(), name='register'),
   url(r'^logout/$', logout, name='logout'),
   url(r'^api-login/$', APILoginView.as_view(), name='api-login')
]

sales/urls.py
from django.contrib import admin
from django.conf.urls import url, include, i18n
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.urls import path


from rest_framework.routers import DefaultRouter

from customauth import urls as auth_urls
from customers import urls as customers_urls
from products.views import ProductViewSet
from products import urls as products_urls
from orders import urls as orders_urls

from .views import IndexView


router = DefaultRouter()
router.register('products', ProductViewSet)

urlpatterns = [
    url(r'^auth/', include(auth_urls, namespace='customauth')),
    url(r'^customers/', include(customers_urls, namespace='customers')),
    url(r'^orders/', include(orders_urls, namespace='orders')),
    url(r'^products/', include(products_urls, namespace='products')),
    url(r'^api-customauth/', include('rest_framework.urls',
                                     namespace='rest_framework')),
    url(r'^api/', include(router.urls)),
    url(r'^$', IndexView.as_view()),
    path('admin/', admin.site.urls),
]

urlpatterns += i18n.i18n_patterns(
    path(r'admin/', admin.site.urls),
)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Shop
        {% endblock %}
    </title>

</head>
<body>
{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'customauth:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'customauth:register' %}">Register or</a>
        <a href="{% url 'customauth:login' %}">Login</a>
        <a href="{% url 'customauth:api-login' %}">API Login</a>
    {% endif %}

{% endblock %}

</body>
</html>